name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build and push Docker image to Docker Hub
      - name: Build and Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t corentin339/20210101:latest .
          docker push corentin339/20210101:latest

      # Log in to Azure Container Registry and push Docker image to ACR
      - name: Log in to Azure Container Registry and push Docker image to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/20210101:latest

      # Login to Azure and deploy to Azure Container Instance
      - name: Login to Azure and deploy to Azure Container Instance
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Container Instance
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: devops-20210101
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20210101:latest
          name: 20210101
          location: francecentral
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          ports: 8081:80
          secure-environment-variables: API_KEY=${{ secrets.API_KEY }}
